# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-12 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='Null', max_length=120),
            preserve_default=False,
        ),
    ]
