# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-04 22:41
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_1',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Letter', 'Letter'), ('Article', 'Article'), ('Image', 'Image'), ('Video', 'Video')], max_length=26, null=True),
        ),
    ]
